name: Deploy Static Website

on:
    schedule:
        - cron: '0 2 * * 3'
    workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Auth to GCP
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: ${{ secrets.GCP_SA_KEY }}
            - name: Configuration to Google SDK
              uses: google-github-actions/setup-gcloud@v2
              with:
                  project_id: ${{ secrets.GCP_PROJECT_ID }}
            - name: Executation and genereation of static website
              uses: appleboy/ssh-action@v0.1.0
              with:
                  host: 34.41.104.35
                  username: github
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd /var/www/html
                      wp simple-static generate

