name: Deploy Static Website

on:
    schedule:
        - cron: '0 2 * * 3'
    workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Auth to GCP
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: ${{ secrets.GCP_SA_KEY }}